[project]
name = "trackgen"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.0",
    "scipy>=1.16.3",
    "scipy-stubs~=1.16.3",
    "pyzmq>=26.0.0",
    "pymap3d>=3.1.0",
    "pydantic>=2.13.2",
]

[project.scripts]
trackgen = "trackgen:main"

[dependency-groups]
dev = [
    "black>=25.12.0",
]

[build-system]
requires = ["uv_build>=0.11.4,<0.12.0"]
build-backend = "uv_build"